# -*- coding: utf-8 -*-
"""HW2_download_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qQx6jfH7GyMtSTKCTELAUuYM4Vd3Jr7
"""

import glob
import os
import numpy as np
import keras
from keras import layers
from urllib import request
import tensorflow as tf

print(tf.__version__)

from google.colab import drive
drive.mount('/content/drive')

# # critters (6 classes)
# classes = ['ant', 'bee', 'butterfly', 'mosquito', 'scorpion', 
#            'spider']

# # birds (6 classes)
# classes = ['bird', 'duck', 'flamingo', 'owl', 'parrot', 
#            'penguin']

# # ocean animals (8 classes)
# classes = ['crab', 'dolphin', 'fish', 'lobster', 'octopus', 
#            'sea turtle', 'shark', 'whale']

# # land mammals (22 classes)
# classes = ['bear', 'camel', 'cat', 'cow', 'dog', 
#            'elephant', 'giraffe', 'hedgehog', 'horse', 'kangaroo', 
#            'lion', 'monkey', 'mouse', 'panda', 'pig', 
#            'rabbit', 'raccoon', 'rhinoceros', 'sheep', 'squirrel', 
#            'tiger', 'zebra']

# all animals (47 classes)
classes = ['ant', 'bat', 'bear', 'bee', 'bird', 
           'butterfly', 'camel', 'cat', 'cow', 'crab', 
           'crocodile', 'dog', 'dolphin', 'duck', 'elephant', 
           'fish', 'flamingo', 'frog', 'giraffe', 'hedgehog', 
           'horse', 'kangaroo', 'lion', 'lobster', 'monkey', 
           'mosquito', 'mouse', 'octopus', 'owl', 'panda', 
           'parrot', 'penguin', 'pig', 'rabbit', 'raccoon', 
           'rhinoceros', 'scorpion', 'sea%20turtle', 'shark', 'sheep', 
           'snail', 'snake', 'spider', 'squirrel',  'tiger', 
           'whale', 'zebra']

api = 'https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/'
data_dir = '/content/drive/My Drive/Colab Notebooks/NNDL/HW2/data/'

def download_bitmaps(api=api, classes=classes):
    for c in classes:
        path = api + c + '.npy'
        print(path)
        c.replace('%20', '_')
        request.urlretrieve(path, data_dir + c + '.npy')

download_bitmaps()

